name: DailySellShop
version: ${project.version}
main: com.dailyshop.DailySellShop
api-version: 1.21
depend: [Vault]
softdepend: [floodgate]
authors: [yangzijian52]
commands:
  ds:
    description: 打开每日收购界面
    usage: /ds [reload]
permissions:
  dailysell.admin:
    description: 允许重载配置
    default: op
